permalink: /en/:year-:month-:day-:title

# show future post, posts might be confusingly hidden through different timezones otherwise
future: true

# the following lines are to make the option {{ page.is_post }} available, thanks to 
# https://stackoverflow.com/questions/18675610/jekyll-change-layout-if-page-is-a-post
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      layout: default-en
      is_post: true # automatically set is_post=true for all posts

kramdown: 
    auto_ids: true  # auto-generate ID's for headings

sass:
  style: compressed

# add plugins
plugins:
  - jekyll-sitemap

# the tools directory contains cached files downloaded from transifex, ignore it
exclude: ["tools"]
