name: Deploy Master Branch

on:
  push:
    branches:
      - master
      - new-deployment

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: Upload
      uses: appleboy/scp-action@master
      env:
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
        HOST: "37.218.242.41"
        PORT: 22
        SOURCE: "_site"
        TARGET: "/var/www/html/"
        rm:

