name: Deploy Preview

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: Upload
      uses: horochx/deploy-via-scp@v1.0.1
      with:
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        host: "37.218.242.41"
        port: 22
        local: "-p _site"
        remote: "/var/www/html/_site/${{ github.sha }}/"
    - name: "post Link"
      uses: rytswd/respost@v0.1.0
      with:
        title: "Preview changes"
        body: "Preview at: http://37.218.242.41/${{ github.sha }}/"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
