# documentation: https://github.com/deltachat/sysadmin/tree/master/delta.chat
name: Push new strings to Transifex

on: 
  pull_request:
    #types: [closed]  # debug
    paths-ignore:
      - 'docs/**'  # only trigger build if a file outside of /docs was changed

jobs:
  push-translations:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y translate-toolkit transifex-client python3-pip
        pip install massedit
    - name: tx init
      run: |
        echo "${{ secrets.transifexrc }}" > ~/.transifexrc
        tx init --user=api --pass=${{ secrets.TXapitoken }}
        tx set --auto-remote https://www.transifex.com/projects/p/delta-chat-pages/
    - name: tx push
      run: |
        tools/t-dance.sh push

